apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: rsyncd
    name: rsyncd
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/rsync/rsyncd:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rsyncd
    name: rsyncd
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: rsyncd:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: http://git.apps.home/demo/rsyncd.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: fedora:22
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: xlZpzmazZGpdQT1Mwe5c
      type: GitHub
    - generic:
        secret: Vwl-iABnLl8HIdfKJNBa
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
