apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsync-modules
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  volumeName: rsync-modules
status: {}
